### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/sensing-space#1]
@LornaLynch Hi, could you have a look over my copy please.

**Comment by LornaLynch** [comment]
Sure: on it now :)

**Comment by LornaLynch** [comment]
Question regarding the list of KS3 learning outcomes: do we need to keep all of these, or separate them into subject areas? There are rather a lot at the moment, and we typically have fewer on resources. @MarcScott

**Comment by MarcScott** [comment]
Hi @LornaLynch , they could be split and trimmed down a little. I'll talk to @MissPhilbin  about it next week.

**Comment by MissPhilbin** [comment]
I'd recommend splitting them into subject areas and cutting them down a little. They should refer to POS bullet points for the key stage. I'm not a science specialist so I'm showing my ignorance of the POS for physics. :)

**Comment by LornaLynch** [comment]
I'm not an education specialist at all, so I'm guessing I'd better defer the cutting to @MarcScott?

**Comment by MarcScott** [comment]
I'll cut them down and categorise.

**Comment by LornaLynch** [comment]
I wondered if it might be a good idea to use a different video for the Zero G flight in Lesson 5? That one is from a channel where the related videos are things like women in bikinis mud wrestling and "Are Models Dumb?". It might be problematic in a class situation! I've found this one with Brian Cox which might be an alternative: https://youtu.be/OZY8279b7BU

**Comment by LornaLynch** [comment]
I think I've checked everything I can do now, though you may want to look at the YouTube video (as noted above). Outstanding issues are listed below (I know some of them can't be closed out yet as they depend on other things, eg resource URL being fixed, guides etc)

Outstanding issues: 
- [x] KS3 bullet points
- [x] URLs in LICENCE, CONTRIBUTING 
- [x] Alternative Zero G video? 
- [x] Update URL in Lesson Plan 2 (Main Dev 9)

**Comment by MarcScott** [comment]
Thanks @LornaLynch I'll get around to fixing these asap

**Comment by MarcScott** [comment]
All fixed thanks - closing
