### ISSUE TITLE
Update URLs

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/sensing-space#3]
The URLs in Contributing/License currently point to "Example Resource". These will need to be updated when the URL is set. Additionally, in the README, I've changed "Example Resource" to Sensing Space, though this may need to be updated if the title changes.

**Comment by LornaLynch** [comment]
Additionally, URL in line 112 of the Lesson 2 Lesson Plan needs to be completed.

**Comment by MarcScott** [comment]
@LornaLynch I've updated the Contrib and license. Will have to wait on the second one, until @bennuttall and I have had a chance to work on publishing the guides sections.

**Comment by LornaLynch** [comment]
Thanks!

**Comment by LornaLynch** [comment]
I'll close this issue and leave a note about the URLs in #1, to save the issue list from getting too cluttered.
