### ISSUE TITLE
SenseHat Temperature readings are fairly inaccurate

### ISSUE THREAD

**Issue by TheSimpleMachine** [raspberrypilearning/sensing-space#5]
Hi, I am fairly new to Raspberry Pi, SenseHat, programming and GitHub.

I was following the [SenseHat tutorial ](https://www.raspberrypi.org/learning/sense-hat-data-logger/worksheet/) and noticed the temperature output from both the pressure and humidity sensors on the SenseHat appears to be off by quite a bit. 

I am assuming the heat from raspberry pi is contributing to the temperature picked up by SensorHat. I removed the pi from it's case which did lower the temperature reading by a few degrees C, but it is still way off.

Note: I noticed the AstroPi encloses the Pi and SenseHat. I am assuming that they are likely getting reliable readings. If, so is there an update that I or the repository (sudo apt-get install sense-hat) is missing?

**Comment by lawsie** [comment]
Hello! Yes, the temperature sensor on the SenseHAT is affected by the Pi. There is some more information about why this happens on this forum thread: https://www.raspberrypi.org/forums/viewtopic.php?f=104&t=111457
